[COMMON] scsi: ufs: Add barrier for sync
Sometimes cdb error was occurred after MMU enabled.
It was synchronization issue between cache and DRAM.
===============================================================
avbops functions are set successfully
First block
Middle blocks
free(tmp_buff)
*out_num_read = num_bytes
SCSI cdb : 28 00 00 00 00 01 00 00 01 00
SCSI Response(01) : SCSI sense : 70 00 05 80 00 00 00 0a 00 00 00 00 24 00 00 00 00 00
Target Failure
CHECK CONDITION
ERROR: Can't read GPT header
avb_cmdline.c:76: ERROR: Error getting unique GUID for partition.
[AVB 2.0 ERR] authentication fail [ret: 0x1] (orange)
===============================================================

Change-Id: I112260b2157a673cb2c7d77c42c043fbb7db3472
Signed-off-by: dukhyun kwon <d_hyun.kwon@samsung.com>